rename branch
CSC207-2022F-UofT/course-project-fixthewifi pull request #24
Opened 2022-11-10 01:20 UTC by xingjianll

Merge the renamed files into main.

2022-11-10 01:25 UTC, JoeZZG approved these changes

2022-11-11 05:47 UTC, thmcheung approved these changes

2022-11-12 01:48 UTC, brendenmcfarlane requested changes
There have been other files committed to main before this was approved (ex: FriendsList.java in the Entities package); it does not look like those files will be retained if we approve this. If we append them to this PR I could approve it.

2022-11-12 02:37 UTC, brendenmcfarlane approved these changes
Looks good!

2022-11-12 02:37 UTC, merged