Feature group chat
CSC207-2022F-UofT/course-project-fixthewifi pull request #64
Opened 2022-12-04 01:10 UTC by brendenmcfarlane

Created Interface adapter layer for usecases Retrieve Friends List and Create Group Chat. I have also created tests for the output adapters, as well as refactored the code at the usecase layer to correctly retrieve the IP address and peer port. I will create controller tests and improve documentation at a later time.

2022-12-05 02:53 UTC, davidlyj approved these changes
Looks good and ready to be merged.

2022-12-06 00:50 UTC, xingjianll requested changes
Good work! Please check the code review comments. Also, use the database's `newChat()` method to make a new chat in the database. I believe the 4th cell (or the 5th i cant remember) in chat.csv is used to store all the member ids (in the format `1-5-2-3-15-26254-123 ...`), make sure the first integer is the admin.

2022-12-06 00:50 UTC, xingjianll commented on src/main/java/server/interface_adapters/create_gc/CreateGCOutputAdapter.java
> +        msg = msg + Constants.SPR + String.valueOf(output_data.getAdmin());
`msg = Constants.GROUP_CHAT + Constants.SPR + String.valueOf(output_data.getAdmin()` would be a simpler implementation of this line.

2022-12-06 00:50 UTC, xingjianll commented on src/main/java/server/usecases/create_gc/CreateGCInteractor.java
> +                input_data.getAdmin(), input_data.getMembers(), peerID, peerPort);
What about the name of the groupchat? A chat has uid, name description, I think at least the uid needs to be sent to the clients

2022-12-06 00:50 UTC, xingjianll commented on src/main/java/server/usecases/create_gc/CreateGCInteractor.java
> +                input_data.getAdmin(), input_data.getMembers(), peerID, peerPort);
Also, you also need to send the groupchat info to other members of the group chat, not just the admin, for example, a user can input `$createchat <chat name> <member uid1> <member uid2> ....` and when a group chat is created the information of the chat will be sent to all members including the admin (I assume the admin is also the person who created the chat?)

2022-12-07 22:51 UTC, merged